name: Abrir PR ao Mover Card

on:
  repository_dispatch:
    types: [PR_OPEN]

permissions:
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can check branches

      - name: Extract issue details
        id: extract
        run: |
          echo "Extracting issue details"
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"
          echo "User Name: ${{ github.event.client_payload.user_name }}"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Check if branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/${{ github.event.client_payload.issue_key }}; then
            echo "Branch exists"
          else
            echo "Branch does not exist"
            exit 1
          fi

      - name: Checkout issue branch
        run: |
          git checkout -b ${{ github.event.client_payload.issue_key }} origin/${{ github.event.client_payload.issue_key }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "develop"
          branch: "${{ github.event.client_payload.issue_key }}"
          title: "PR para a issue ${{ github.event.client_payload.issue_key}} criado por ${{ github.event.client_payload.user_name }} (triggered by ${{ github.actor }})"
          body: |
            Este PR resolve a issue ${{ github.event.client_payload.issue_key}}.
            Criado por ${{ github.event.client_payload.user_name }} e acionado por ${{ github.actor }}.
