name: Jira to GitHub Workflow

on:
  workflow_dispatch:
    inputs:
      jira_card_key:
        description: 'Jira Card Key'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Jira Card Key
      run: echo "Jira Card Key is ${{ github.event.inputs.jira_card_key }}"
